version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/typescript"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Australia/Melbourne"
    open-pull-requests-limit: 5
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/typescript/jarvis-console-01"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Australia/Melbourne"
    open-pull-requests-limit: 5
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Australia/Melbourne"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
