import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

import { api } from "../../convex/_generated/api.js";
import { ConvexHttpClient } from "convex/browser";

export type AssistantState = {
  lastIntent?: string;
  lastInput?: string;
  lastResult?: unknown;
  lastReminder?: unknown;
  [key: string]: unknown;
};

export interface PersistenceProvider {
  loadState(): Promise<AssistantState>;
  saveState(state: AssistantState): Promise<void>;
}

function defaultDataPath(): string {
  const __filename = fileURLToPath(import.meta.url);
  return path.resolve(path.dirname(__filename), "../../data/jarvis-state.json");
}

export class JSONPersistence implements PersistenceProvider {
  private filePath: string;

  constructor(filePath?: string) {
    this.filePath = filePath ?? defaultDataPath();
  }

  async loadState(): Promise<AssistantState> {
    try {
      const raw = await fs.readFile(this.filePath, { encoding: "utf8" });
      try {
        return JSON.parse(raw) as AssistantState;
      } catch (err) {
        throw new Error(`Malformed JSON in state file ${this.filePath}: ${(err as Error).message}`);
      }
    } catch (err: any) {
      if (err.code === "ENOENT") {
        return {};
      }
      throw err;
    }
  }

  async saveState(state: AssistantState): Promise<void> {
    const dir = path.dirname(this.filePath);
    await fs.mkdir(dir, { recursive: true });
    const payload = JSON.stringify(state, null, 2);
    await fs.writeFile(this.filePath, payload, { encoding: "utf8" });
  }
}

// Narrow injected client interface for tests and runtime; avoid using `any`.
export interface ConvexClientLike {
  query<T>(fnRef: unknown, args?: unknown): Promise<T>;
  mutation<T>(fnRef: unknown, args?: unknown): Promise<T>;
}

export class ConvexPersistence implements PersistenceProvider {
  private client: ConvexClientLike;

  constructor(client?: ConvexClientLike) {
    const provider = (process.env.PERSISTENCE_PROVIDER ?? "json").toLowerCase();
    if (provider !== "json" && provider !== "convex") {
      throw new Error(`Invalid PERSISTENCE_PROVIDER '${process.env.PERSISTENCE_PROVIDER}'. Valid values: unset, json, convex.`);
    }

    if (provider === "convex" && !process.env.CONVEX_URL) {
      throw new Error("PERSISTENCE_PROVIDER=convex requires CONVEX_URL to be set in the environment.");
    }

    if (client) {
      this.client = client;
    } else {
      // Use the official documented Convex HTTP client for Node CLI usage.
      const convexUrl = process.env.CONVEX_URL as string | undefined;
      if (!convexUrl) {
        // This should not happen because we checked above, but keep the guard.
        throw new Error("Missing CONVEX_URL for ConvexPersistence construction.");
      }
      // ConvexHttpClient in the installed convex package exposes query/mutation and accepts function refs generated by codegen.
      this.client = new ConvexHttpClient(convexUrl) as unknown as ConvexClientLike;
    }
  }

  async loadState(): Promise<AssistantState> {
    // Use the generated API function reference
    const row = await this.client.query<{ id: string; state: Record<string, unknown> } | null>(api.assistantState.get);
    if (!row) return {};
    return (row.state ?? {}) as AssistantState;
  }

  async saveState(state: AssistantState): Promise<void> {
    // Call the generated upsert mutation with the explicit shape { state }
    await this.client.mutation(api.assistantState.upsert, { state });
  }
}

export function createPersistenceFromEnv(client?: ConvexClientLike): PersistenceProvider {
  const providerRaw = process.env.PERSISTENCE_PROVIDER ?? "";
  const provider = providerRaw.toLowerCase();
  if (provider === "" || provider === "json") {
    return new JSONPersistence();
  }
  if (provider === "convex") {
    return new ConvexPersistence(client);
  }
  throw new Error(`Invalid PERSISTENCE_PROVIDER '${process.env.PERSISTENCE_PROVIDER}'. Valid values are unset, json, convex.`);
}
