export const HTTP_APP_CONFIG = Symbol("HTTP_APP_CONFIG");
export const HTTP_PERSISTENCE = Symbol("HTTP_PERSISTENCE");
export const HTTP_PROVIDER_NAME = Symbol("HTTP_PROVIDER_NAME");
export const HTTP_RECONCILIATION_HEALTH = Symbol("HTTP_RECONCILIATION_HEALTH");
export const HTTP_EXTERNAL_RECONCILIATION_READ_STORE = Symbol(
  "HTTP_EXTERNAL_RECONCILIATION_READ_STORE",
);
export const HTTP_TOTALITY_PIPELINE = Symbol("HTTP_TOTALITY_PIPELINE");
export const HTTP_MEMORY_CHANGE_SETS = Symbol("HTTP_MEMORY_CHANGE_SETS");
export const HTTP_TOOL_ACTIONS = Symbol("HTTP_TOOL_ACTIONS");
export const HTTP_TOOL_EXECUTION = Symbol("HTTP_TOOL_EXECUTION");
export const HTTP_OBSERVABILITY_REPORTER = Symbol("HTTP_OBSERVABILITY_REPORTER");
export const HTTP_CLIENT_STORE = Symbol("HTTP_CLIENT_STORE");
export const HTTP_PROJECT_STORE = Symbol("HTTP_PROJECT_STORE");
export const HTTP_QUOTE_STORE = Symbol("HTTP_QUOTE_STORE");
export const HTTP_QUOTE_REPOSITORY = Symbol("HTTP_QUOTE_REPOSITORY");
export const HTTP_QUOTE_DELIVERY_REPOSITORY = Symbol("HTTP_QUOTE_DELIVERY_REPOSITORY");
export const HTTP_ERRAND_STORE = Symbol("HTTP_ERRAND_STORE");
export const HTTP_BUILD_STORE = Symbol("HTTP_BUILD_STORE");
export const HTTP_BUILD_LOG_STORE = Symbol("HTTP_BUILD_LOG_STORE");
export const HTTP_UPGRADE_STORE = Symbol("HTTP_UPGRADE_STORE");
export const HTTP_ASSET_STORE = Symbol("HTTP_ASSET_STORE");
export const HTTP_PREFERENCE_STORE = Symbol("HTTP_PREFERENCE_STORE");
export const HTTP_NOTE_STORE = Symbol("HTTP_NOTE_STORE");
export const HTTP_ACTIVITY_EVENTS = Symbol("HTTP_ACTIVITY_EVENTS");
