export const HTTP_APP_CONFIG = Symbol("HTTP_APP_CONFIG");
export const HTTP_PERSISTENCE = Symbol("HTTP_PERSISTENCE");
export const HTTP_PROVIDER_NAME = Symbol("HTTP_PROVIDER_NAME");
export const HTTP_TOTALITY_PIPELINE = Symbol("HTTP_TOTALITY_PIPELINE");
