export const HTTP_APP_CONFIG = Symbol("HTTP_APP_CONFIG");
export const HTTP_PERSISTENCE = Symbol("HTTP_PERSISTENCE");
export const HTTP_PROVIDER_NAME = Symbol("HTTP_PROVIDER_NAME");
export const HTTP_TOTALITY_PIPELINE = Symbol("HTTP_TOTALITY_PIPELINE");
export const HTTP_MEMORY_CHANGE_SETS = Symbol("HTTP_MEMORY_CHANGE_SETS");
export const HTTP_TOOL_ACTIONS = Symbol("HTTP_TOOL_ACTIONS");
export const HTTP_CLIENT_STORE = Symbol("HTTP_CLIENT_STORE");
