import { v } from "convex/values";
import { safetyBindingValidator } from "./safetyBindingValidators.js";

export const toolExecutionStatusValidator = v.union(
  v.literal("dry-run"),
  v.literal("succeeded"),
  v.literal("failed"),
  v.literal("indeterminate"),
  v.literal("blocked"),
);

export const toolExecutionErrorCodeValidator = v.union(
  v.literal("not-authorized"),
  v.literal("not-allowlisted"),
  v.literal("invalid-arguments"),
  v.literal("indeterminate"),
  v.literal("failed"),
  v.literal("fingerprint-mismatch"),
  v.literal("provider-failed"),
  v.literal("provider-reference-missing"),
  v.literal("retry-blocked-pending-reconciliation"),
  v.literal("reconciliation-escalated"),
  v.literal("reconciliation-unavailable"),
  v.literal("approval-expired"),
  v.literal("approval-consumed"),
  v.literal("precondition-failed"),
  v.literal("safety-blocked"),
);

export const toolExecutionActorValidator = v.union(
  v.literal("user"),
  v.literal("agent"),
  v.literal("tool"),
);

export const toolExecutionReceiptInputValidator = v.object({
  receiptId: v.string(),
  actionId: v.string(),
  requestId: v.string(),
  projectId: v.string(),
  idempotencyKey: v.string(),
  actionFingerprint: v.string(),
  effectFingerprint: v.optional(v.string()),
  tool: v.string(),
  operation: v.string(),
  actor: toolExecutionActorValidator,
  approvalId: v.optional(v.string()),
  policyVersion: v.string(),
  correlationId: v.string(),
  source: v.string(),
  provider: v.optional(v.string()),
  providerRequestId: v.optional(v.string()),
  providerCorrelationId: v.optional(v.string()),
  reconciliationId: v.optional(v.string()),
  status: toolExecutionStatusValidator,
  outputDigest: v.optional(v.string()),
  errorCode: v.optional(toolExecutionErrorCodeValidator),
  providerErrorCode: v.optional(v.string()),
  startedAt: v.number(),
  completedAt: v.number(),
  safetyBinding: v.optional(safetyBindingValidator),
});

export const toolExecutionReceiptDocumentValidator = v.object({
  _id: v.id("toolExecutionReceipts"),
  _creationTime: v.number(),
  ownerId: v.string(),
  receiptKey: v.string(),
  receiptId: v.string(),
  actionId: v.string(),
  requestId: v.optional(v.string()),
  projectId: v.string(),
  idempotencyKey: v.string(),
  actionFingerprint: v.string(),
  effectFingerprint: v.optional(v.string()),
  tool: v.string(),
  operation: v.string(),
  actor: v.optional(toolExecutionActorValidator),
  approvalId: v.optional(v.string()),
  policyVersion: v.optional(v.string()),
  correlationId: v.optional(v.string()),
  source: v.optional(v.string()),
  provider: v.optional(v.string()),
  providerRequestId: v.optional(v.string()),
  providerCorrelationId: v.optional(v.string()),
  reconciliationId: v.optional(v.string()),
  status: toolExecutionStatusValidator,
  outputDigest: v.optional(v.string()),
  errorCode: v.optional(toolExecutionErrorCodeValidator),
  providerErrorCode: v.optional(v.string()),
  startedAt: v.number(),
  completedAt: v.number(),
  createdAt: v.number(),
  safetyBinding: v.optional(safetyBindingValidator),
});
